{"status":"ERROR","subtests":[{"name":"Cache.add called with no arguments","status":"FAIL"},{"name":"Cache.add called with relative URL specified as a string","status":"FAIL"},{"name":"Cache.add called with non-HTTP/HTTPS URL","status":"FAIL"},{"name":"Cache.add called with Request object","status":"FAIL"},{"name":"Cache.add called with POST request","status":"FAIL"},{"name":"Cache.add called twice with the same Request object","status":"FAIL"},{"name":"Cache.add with request with null body (not consumed)","status":"FAIL"},{"name":"Cache.add with 206 response","status":"FAIL"},{"name":"Cache.addAll with 206 response","status":"FAIL"},{"name":"Cache.add with request that results in a status of 404","status":"FAIL"},{"name":"Cache.add with request that results in a status of 500","status":"FAIL"},{"name":"Cache.addAll with no arguments","status":"FAIL"},{"name":"Cache.addAll with a mix of valid and undefined arguments","status":"FAIL"},{"name":"Cache.addAll with an empty array","status":"FAIL"},{"name":"Cache.addAll with string URL arguments","status":"FAIL"},{"name":"Cache.addAll with Request arguments","status":"FAIL"},{"name":"Cache.addAll with a mix of succeeding and failing requests","status":"FAIL"},{"name":"Cache.addAll called with the same Request object specified twice","status":"FAIL"}]}